
# The used C++ compiler
CPP=$(CXX)

# Additional compilation flags
CPPFLAGS=-Wall -Werror -std=c++98 -O2 -march=native -msse -funroll-loops -lpng -ltiff -lz #-msse2 -funroll-loops
#CPPFLAGS=-Wall -Werror -std=c++98 -g -ggdb

####
#### External dependency configuration
####

# GetFEM matrix library, GMM, version 3.0 or higher
GMM_INCLUDE=-I/opt/gmm-3.0/include

# COIN-OR Open Solver Interface (Osi), version 0.97.1 or higher
COIN_INCLUDE=-I/opt/coin-osi-0.97.1/include
COIN_LIB=-L/opt/coin-osi-0.97.1/lib -lOsiClp -lOsi -lClp -lCoinUtils -lm \
	-L/usr/lib/sse2 -llapack_atlas -lf77blas -latlas -lcblas -lg2c \
	-L/usr/lib/atlas/sse2 -lblas

# libboosting
#BOOSTING_INCLUDE=-I/data/home/scut/mpi/nowozin/projects/libboosting/include
#BOOSTING_LIB=$(COIN_LIB) /data/home/scut/mpi/nowozin/projects/libboosting/src/libboosting.a

# libvigra
VIGRA_INCLUDE=`vigra-config --cppflags`
VIGRA_LIB=`vigra-config --libs`

# libxml++2.6
XMLPP_INCLUDE=`pkg-config --cflags libxml++-2.6`
XMLPP_LIB=`pkg-config --libs libxml++-2.6`

# boost library
BOOST_LIB=-lboost_program_options -lboost_filesystem

# CPP unit
CPPUNIT_LIB=-lcppunit


####
#### Internal dependencies
####
FEATURES_UTILITY_LIB=../utility/libutility.a
FEATURES_LIB=../features/libfeatures.a

###
INCLUDE=-I../classifier -I../features -I../utility -I../external -I../ \
	$(GMM_INCLUDE) $(COIN_INCLUDE) $(BOOSTING_INCLUDE) $(VIGRA_INCLUDE) \
	$(XMLPP_INCLUDE)

# default rule
%.o: %.cpp
	$(CPP) $(CPPFLAGS) $(INCLUDE) -c $^ -o $@

